# GENERATED by scripts/pipeline.py --makefile -- do not edit; edit GRAPH there.
PY ?= python
R  := results
.PHONY: all clean-json
all: $(R)/surface_baseline.json $(R)/null_control.json $(R)/field_construction.json $(R)/direction_geometry_v11_validated.json $(R)/direction_geometry_v11_lasttoken.json $(R)/direction_geometry_v11_validated_smollm2.json $(R)/corrected_decomposition_validated.json $(R)/label_permuted_control_validated.json $(R)/released_label_permuted.json $(R)/wrapper_curves.json $(R)/slope_distribution_deploy_peak_lf.json $(R)/concordance_equivalence_peak_lf.json $(R)/counterbalance_saturation.json $(R)/imbalance_hazard.json $(R)/arm_decomposition_trunk_peak_validated.json $(R)/implementation_facet.json $(R)/gstudy_gtheory_deploy_peak_lf.json $(R)/reml_components_validated_interior.json $(R)/reml_components_validated_interior_fourfam.json $(R)/two_concept_floor.json $(R)/qwen_anomaly_test.json $(R)/slope_reliability.json $(R)/param_count_check.json $(R)/k_requirement.json $(R)/reanalysis_table.json

$(R)/surface_baseline.json:
	$(PY) scripts/surface_baseline.py

$(R)/null_control.json:
	$(PY) scripts/null_control.py

$(R)/field_construction.json:
	$(PY) scripts/field_construction_check.py --report

$(R)/direction_geometry_v11_validated.json:
	$(PY) scripts/direction_geometry.py --data v11 --pooling validated

$(R)/direction_geometry_v11_lasttoken.json:
	$(PY) scripts/direction_geometry.py --data v11 --pooling lasttoken

$(R)/direction_geometry_v11_validated_smollm2.json:
	$(PY) scripts/direction_geometry.py --data v11 --pooling validated --models smollm2-135m,smollm2-360m,smollm2-1.7b --suffix _smollm2

$(R)/corrected_decomposition_validated.json:
	$(PY) scripts/corrected_decomposition.py --pooling validated

$(R)/label_permuted_control_validated.json:
	$(PY) scripts/label_permuted_control.py --pooling validated

$(R)/released_label_permuted.json:
	$(PY) scripts/released_label_permuted.py --report

$(R)/wrapper_curves.json:
	$(PY) scripts/wrapper_curves.py

$(R)/slope_distribution_deploy_peak_lf.json:
	$(PY) scripts/slope_distribution.py --sad-pooling lf

$(R)/concordance_equivalence_peak_lf.json:
	$(PY) scripts/concordance_equivalence.py

$(R)/counterbalance_saturation.json:
	$(PY) scripts/counterbalance_saturation.py

$(R)/imbalance_hazard.json:
	$(PY) scripts/imbalance_hazard.py

$(R)/arm_decomposition_trunk_peak_validated.json:
	$(PY) scripts/arm_decomposition.py

$(R)/implementation_facet.json:
	$(PY) scripts/implementation_facet.py

$(R)/gstudy_gtheory_deploy_peak_lf.json:
	$(PY) scripts/gstudy_gtheory.py --sad-pooling lf

$(R)/reml_components_validated_interior.json:
	$(PY) scripts/reml_components.py

$(R)/reml_components_validated_interior_fourfam.json:
	$(PY) scripts/reml_components.py --data v11 --models qwen2.5-0.5b,qwen2.5-1.5b,qwen2.5-3b,qwen2.5-7b,gemma2-2b,llama3.2-1b,llama3.2-3b,smollm2-135m,smollm2-360m,smollm2-1.7b --suffix _fourfam

$(R)/two_concept_floor.json: $(R)/null_control.json
	$(PY) scripts/two_concept_floor.py

$(R)/qwen_anomaly_test.json: $(R)/wrapper_curves.json
	$(PY) scripts/qwen_anomaly_test.py

$(R)/slope_reliability.json:
	$(PY) scripts/slope_reliability.py

$(R)/param_count_check.json: $(R)/wrapper_curves.json
	$(PY) scripts/param_count_check.py

$(R)/k_requirement.json:
	$(PY) scripts/k_requirement.py

$(R)/reanalysis_table.json: $(R)/slope_distribution_deploy_peak_lf.json $(R)/released_label_permuted.json
	$(PY) scripts/reanalysis_table.py

clean-json:
	rm -f $(R)/*.json
